const MENU_ITEMS = {
  main: [
    {
      slug: 'home',
      active: false,
      path: 'index.html',
      icon: ['fa-solid', 'fa-house'],
      label: 'Home',
    },
    {
      slug: 'about',
      active: false,
      path: 'about.html',
      icon: ['fa-solid', 'fa-info'],
      label: 'Sobre',
    },
    {
      slug: 'contact',
      active: false,
      path: 'index.html#contact',
      icon: ['fa-solid', 'fa-phone'],
      label: 'Contato',
    },
  ],
  default: [
    {
      slug: 'agricultura-familiar',
      active: false,
      path: 'agricultura-familiar',
      icon: ['fa-solid', 'fa-people-roof'],
      label: 'Agricultura Familiar',
    },
    {
      slug: 'alimentacao-escolar',
      active: false,
      path: 'alimentacao-escolar',
      icon: ['fa-solid', 'fa-apple-whole'],
      label: 'Alimentação Escolar',
    },
    {
      slug: 'comsea',
      active: false,
      path: 'comsea',
      icon: ['fa-solid', 'fa-file-lines'],
      label: 'COMSEA',
    }, {
      slug: 'panificadora-social',
      active: false,
      path: 'panificadora-social',
      icon: ['fa-solid', 'fa-bread-slice'],
      label: 'Panificadora Social',
    }, {
      slug: 'banco-de-alimentos',
      active: false,
      path: 'banco-de-alimentos',
      icon: ['fa-solid', 'fa-boxes-stacked'],
      label: 'Banco de Alimentos',
    },
    {
      slug: 'caisan',
      active: false,
      path: 'caisan',
      icon: ['fa-solid', 'fa-file-lines'],
      label: 'Caisan',
    },
    {
      slug: 'cozinha-social',
      active: false,
      path: 'cozinha-social',
      icon: ['fa-solid', 'fa-drumstick-bite'],
      label: 'Cozinha Social',
    },
    {
      slug: 'casas-abrigo',
      active: false,
      path: 'casas-abrigo',
      icon: ['fa-solid', 'fa-person-shelter'],
      label: 'Casas Abrigo',
    },
    {
      slug: 'restaurantes',
      active: false,
      path: 'restaurantes',
      icon: ['fa-solid', 'fa-utensils'],
      label: 'Restaurantes',
    },
  ],
};
